### ISSUE TITLE
printing of console-stamp main.js in all logs as well as new line for each log

### ISSUE THREAD

**Issue by aaron-axisa** [starak/node-console-stamp#22]
I have filed this issue on stack overflow (to avoid duplication) :  [issue](http://stackoverflow.com/questions/40803959/console-stamp-adding-new-lines-and-needless-main-js-path)

**Comment by starak** [comment]
I'm guessing this is a feature in Jest and therefore not an issue here.

But interesting! I'll do some research on it :)

**Comment by sisou** [comment]
This is most likely caused by jest.js, as seen here:
https://github.com/facebook/jest/blob/master/packages/jest-cli/src/lib/BufferedConsole.js#L36

In the jest-cli module, they use the BufferedConsole that outputs the file and line number by default when you use console.log in tests (which you shouldn't, I guess).

So it's not this module's fault, but coming from the jest code.

**Comment by starak** [comment]
I've looked in to this and @sisou is right. Jest is intercepting the console calls and writes to the stdout/stderr stream. 

I'm therefore closing this
