### ISSUE TITLE
Console stamp removes default coloring

### ISSUE THREAD

**Issue by crrdean** [starak/node-console-stamp#64]
Without console-stamp, arrays, objects, etc. will show up in color.  After adding console-stamp, everything turns into a default text color.

![image](https://user-images.githubusercontent.com/56645870/221664545-39a0e06b-3267-42d1-ab51-db9db9499822.png)

![image](https://user-images.githubusercontent.com/56645870/221664588-0efa15e0-dffc-48e5-8532-d336723ed45a.png)

**Comment by starak** [comment]
Hi @crrdean,

Thank you for bringing this to our attention.

The behaviour you've observed is a known limitation due to the way console-stamp modifies the console output. When intercepting and stamping the logs, certain native coloring functionalities from the console are overridden, resulting in the default text color you're seeing.

While we would love to maintain the native coloring of the console, doing so presents complexities that make it challenging to implement without potential side effects or issues.

We appreciate your understanding and feedback. Closing this issue for now, but please feel free to reach out if you have further questions or suggestions.

**Comment by crrdean** [comment]
Understood.  Thank you for the explanation.
